# Generated by Django 5.1.1 on 2024-10-27 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Файл видео')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
