# Generated by Django 5.1.1 on 2024-10-27 18:26

import app.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='file',
            field=models.FileField(upload_to=app.videos.models.video_upload_path, verbose_name='Файл видео'),
        ),
    ]
