# Generated by Django 5.1.1 on 2024-10-31 09:03

import app.videos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videomodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='description',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='wish_message',
            field=models.TextField(blank=True, verbose_name='wish-message'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='author',
            field=models.CharField(max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='upload-date'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='file',
            field=models.FileField(upload_to=app.videos.models.video_upload_path, verbose_name='video-file'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='video-title'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update-date'),
        ),
    ]
