# Generated by Django 4.2.5 on 2024-11-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_videomodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HLS Playlist'),
        ),
    ]
