# Generated by Django 4.2.5 on 2024-11-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videomodel_hls_playlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomodel',
            options={'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
    ]
